import type { NextPage } from "next";
import Head from "next/head";
import Layout from "@/components/layout/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>
          MR Group - надежный девелопер недвижимости в Москве | Продажа квартир
          в новостройках бизнес и премиум-класса | Официальный сайт
        </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Hello world</h1>
      </Layout>
    </>
  );
};

export default Home;
